from cluster import *
from union import *

def make_one_union():
    u = ClusterUnion()
    
    u.add_cluster(Cluster(["geradezus (ugs.", "regional)", "schier (geh.)", "geradezu", "gerade", "schlicht und einfach", "rein (ugs.)", "rundheraus", "schlechthin (geh.)", "reinwegs", "schlichtwegs", "glattwegs", "schlechtwegs", "platterdings", "schlechterdings (geh.", "veraltend)", "schlicht", "freilich (ugs.", "süddt.)", "gradweg (ugs.)", "nachgerade (geh.)", "direktemang (ugs.)", "glattweg", "durchaus", "schlankweg (ugs.)", "einfach", "schlechtweg", "schlankwegs", "direkt", "rundweg", "schlichtweg", "glatt", "geradewegs", "reinweg", "reinewegs", "praktisch (ugs.)"]))
    u.add_cluster(Cluster(["offenherzig", "freimütig", "gradheraus (ugs.)", "unverblümt", "frei heraus", "geradeheraus", "frei", "rundheraus", "offen", "direkt"]))
    u.add_cluster(Cluster(["geradlinig", "ohne Umweg", "frontal", "ohne Umwege", "direkt", "geradeaus"]))
    u.add_cluster(Cluster(["wellenlos", "gerade", "glatt", "topfeben (Verstärkung)", "platt (ugs.)", "waagrecht", "planar", "eben", "flächig", "flach", "waagerecht", "plan", "gleichmäßig"]))
    u.add_cluster(Cluster(["waagerecht", "waagrecht", "horizontal"]))
    u.add_cluster(Cluster(["stetig", "gleichmäßig", "unbeirrbar"]))
    u.add_cluster(Cluster(["klipp und klar (ugs.)", "geradewegs"]))
    u.add_cluster(Cluster(["ungezwungen", "frei", "ungebunden", "ungehindert", "zwanglos"]))
    u.add_cluster(Cluster(["sozial", "freundlich", "kontaktfreudig", "offen", "leutselig", "extrovertiert", "extravertiert"]))
    u.add_cluster(Cluster(["wie geschmiert (ugs.)", "einfach", "ohne Schwierigkeiten", "ohne Probleme", "reibungslos", "anstandslos", "wie am Schnürchen (ugs.)", "problemlos (Hauptform)", "klaglos (österr.)", "wie ein Glöckerl (ugs.", "österr.)", "umstandslos", "mühelos", "störungsfrei", "unaufwändig"]))
    u.add_cluster(Cluster(["ausgerechnet", "gerade", "justament", "just"]))
    u.add_cluster(Cluster(["immerfort", "ohne Unterbrechung", "kontinuierlich", "fortlaufend", "fortdauernd", "stetig"]))
    u.add_cluster(Cluster(["faltenfrei", "glatt wie ein Babypopo", "makellos glatt", "glatt", "faltenlos", "glatt wie ein Kinderpopo"]))
    u.add_cluster(Cluster(["in optima forma (geh.", "lat.)", "ohne den kleinsten Fehler", "vollkommen", "fehlerlos", "tadellos", "tippi toppi (ugs.)", "ideal", "fehlerfrei", "vorbildhaft", "vortrefflich", "mustergültig", "vollendet", "einwandfrei", "einwandlos", "ohne Fehl und Tadel", "makellos", "tipptopp (ugs.)", "vorzüglich", "klaglos (österr.)", "untadelig", "vorbildlich", "perfekt", "in bestem Zustand (variabel)"]))
    u.add_cluster(Cluster(["stet", "stetig"]))
    u.add_cluster(Cluster(["schicklich", "anständig", "salonfähig", "einwandfrei", "korrekt"]))
    u.add_cluster(Cluster(["prompt", "schnurstracks (ugs.)", "ungesäumt (geh.", "veraltend)", "ohne Umwege", "stracks", "(jetzt) gleich (ugs.)", "augenblicklich", "ohne Zeitverzug", "instantan", "fristlos", "auf dem Fuß folgend (ugs.)", "umgehend", "am besten gestern (ugs.)", "schleunigst", "sogleich", "unmittelbar", "unverzüglich (Hauptform)", "alsbald (geh.)", "stante pede (lat.)", "geradewegs", "direkt", "auf der Stelle", "stehenden Fußes (geh.)", "postwendend", "sofort"]))
    u.add_cluster(Cluster(["einfach", "banal", "(ganz) normal", "kunstlos", "gewöhnlich", "unspektakulär", "simpel", "schlicht"]))
    u.add_cluster(Cluster(["gerade", "eben (ugs.)", "soeben", "vor einem Moment", "vor wenigen Momenten", "grade (ugs.)", "just", "gerade eben (Hauptform)", "vor ein paar Sekunden", "justament", "frisch"]))
    u.add_cluster(Cluster(["kontaktfreudig", "gesellig"]))
    u.add_cluster(Cluster(["der letzte Schrei (ugs.", "fig.)", "neu (entstanden) (Hauptform)", "neu auf dem Markt", "neuartig", "frisch", "eigene Wege gehen(d) (fig.)", "noch nicht dagewesen", "(noch) nie dagewesen", "neu entwickelt", "innovativ", "originell"]))
    u.add_cluster(Cluster(["rein (ugs.)", "hinein", "in"]))
    u.add_cluster(Cluster(["zutreffend", "richtig (Hauptform)", "exakt", "korrekt", "goldrichtig (ugs.)"]))
    u.add_cluster(Cluster(["untief", "seicht", "flach"]))
    u.add_cluster(Cluster(["alle (ugs.)", "schlapp", "duhne (ugs.", "rheinisch)", "lurig (ugs.", "rheinisch)", "matt", "daneben (ugs.)", "lasch", "kraftlos", "in den Seilen hängen (ugs.)", "keine Energie mehr haben", "platt (ugs.)", "ausgepowert (ugs.)", "schlaff", "ohne Saft und Kraft (ugs.)", "nüntig (ugs.", "schweiz.", "selten", "vorarlbergerisch)", "fix und foxi (ugs.", "scherzhaft", "veraltet)", "down (ugs.", "veraltend)", "geschafft (ugs.)", "(es .. einfach) nicht mehr gehen (ugs.)", "abgeschlafft", "groggy (ugs.)", "saft- und kraftlos", "kaputt (ugs.)", "ausgelutscht (ugs.)"]))
    u.add_cluster(Cluster(["ehrlich", "lauter", "aufrichtig", "grundanständig", "grundehrlich", "unverstellt", "patent", "grundgut", "fair", "lauteren Herzens (geh.", "veraltend)", "ehrbar", "treu und brav", "veritabel", "redlich", "anständig", "treu", "geradeheraus", "kreuzbrav", "das Herz am rechten Fleck haben (fig.", "sprichwörtlich)", "rechtschaffen", "aufrecht", "wahrhaft", "honett (geh.)"]))
    u.add_cluster(Cluster(["(das) gemeine Volk", "(die) Leute (ugs.)", "(die) breite Masse", "(die) Allgemeinheit", "(die) Menschen (in einem Gebiet)", "man allgemein (ugs.)", "alle (ugs.)"]))
    u.add_cluster(Cluster(["richtig", "bis über beide Ohren (ugs.", "fig.)", "ganz und gar", "komplett", "absolut", "vollständig", "völlig", "sowas von (ugs.", "emotional)", "in jeder Hinsicht", "mit Haut und Haaren (ugs.", "fig.)", "rundweg", "mit Herz und Seele (ugs.)", "jeder Zoll ein / eine ... (ugs.)", "vollends", "durchweg", "hundertprozentig", "ganz (Gradadverb) (Hauptform)", "vollauf", "total", "in vollem Umfang", "gänzlich", "durchwegs (süddt.", "österr.)", "durch und durch", "vollkommen", "rundum", "herzlich (ugs.", "emotional)", "voll (ugs.", "jugendsprachlich)", "vollumfänglich"]))
    u.add_cluster(Cluster(["oberflächlich", "seicht", "belanglos", "platt (ugs.)", "flach", "ohne Tiefgang", "ohne tiefere Bedeutung"]))
    u.add_cluster(Cluster(["tief", "flach", "niedrig"]))
    u.add_cluster(Cluster(["futuristisch", "progressiv", "zukunftsweisend", "richtungsweisend", "innovativ", "seiner Zeit voraus", "avant la lettre (geh.", "franz.)", "fortschrittlich"]))
    u.add_cluster(Cluster(["in Zeit und Ewigkeit", "kontinuierlich", "stets", "allweil (süddt.)", "immer nur", "allzeit", "immer (Hauptform)", "alleweil (süddt.)", "immer und ewig", "ständig", "perpetuierlich (geh.)", "perpetuell (geh.)", "persistent", "stetig", "immerwährend", "immerdar", "fortwährend", "stets und ständig", "konstant"]))
    u.add_cluster(Cluster(["unbeeinträchtigt", "ungestört", "störungsfrei", "in Ruhe", "ohne Störung"]))
    u.add_cluster(Cluster(["sitzen geblieben", "ledig", "alleinstehend", "keine(n) abbekommen (haben) (ugs.", "abwertend)", "Single", "unverheiratet", "allein", "ohne Mann", "ohne Partner", "solo", "ohne Partner (lebend)", "ohne Partnerin", "unvermählt", "hat keinen abgekriegt (ugs.", "abwertend)", "partnerlos", "unbeweibt (scherzhaft", "veraltet)", "ohne Frau", "unverehelicht (fachspr.", "Papierdeutsch)", "ungebunden", "allein lebend", "ohne feste Bindung", "(noch) frei", "unbemannt", "nicht liiert", "(noch) zu haben", "nicht verpartnert (Amtsdeutsch)", "ehelos"]))
    u.add_cluster(Cluster(["unzweifelhaft", "seien Sie versichert (dass) (geh.)", "in jeder Hinsicht", "todsicher (ugs.)", "ohne Zweifel", "allemal (ugs.)", "außer Zweifel", "jedenfalls (ugs.)", "sei versichert (dass) (geh.)", "hundertpro (ugs.)", "auf jeden Fall (ugs.)", "gewiss", "unter allen Umständen", "mit Bestimmtheit", "mit Sicherheit", "zweifelsohne", "sicherlich (ugs.", "Hauptform)", "auf alle Fälle (ugs.)", "(so) sicher wie das Amen in der Kirche", "ganz bestimmt", "bestimmt", "ohne Frage", "zweifellos", "es sei Ihnen versichert (dass) (geh.)", "worauf du dich verlassen kannst! (ugs.", "Redensart)", "unausweichlich", "unbedingt", "definitiv", "in jedem Fall", "wahrlich", "sicher", "absolut", "partout (ugs.)", "(ey Alter,) ich schwör (Jugendsprache", "Substandard) (ugs.)", "worauf du einen lassen kannst (ugs.", "scherzhaft)", "unweigerlich", "fraglos", "so gut wie sicher", "komme was (da) wolle"]))
    u.add_cluster(Cluster(["patent", "dienlich", "zweckdienlich", "geschickt (ugs.", "süddt.)", "praxistauglich", "empfiehlt sich", "empfehlenswert", "praktikabel", "praktisch", "zweckmäßig"]))
    u.add_cluster(Cluster(["nackt", "unverblümt", "unverhüllt"]))
    u.add_cluster(Cluster(["verhältnismäßig", "eher", "nicht un...", "halb", "mäßig (geh.)", "schon ganz (ugs.)", "durchaus", "ziemlich", "leidlich (geh.)", "in Grenzen (geh.)", "vergleichsweise", "halbwegs (ugs.)", "ganz schön (ugs.)", "relativ", "reichlich", "hinlänglich (geh.)", "einigermaßen (Hauptform)", "ganz (ugs.)", "recht (ugs.)"]))
    u.add_cluster(Cluster(["gesittet", "rein", "tugendsam", "vernünftig (ugs.)", "moralisch", "sittsam", "moralinsauer (geh.", "abwertend)", "züchtig", "tugendhaft", "standhaft", "anständig", "moralistisch (oft abwertend) (geh.)", "ordentlich (ugs.)"]))
    u.add_cluster(Cluster(["Alleinstehender", "Single", "Junggeselle", "Unverheirateter", "nicht Liierter", "Alleinlebender"]))
    u.add_cluster(Cluster(["regelmäßig", "gleichmäßig", "in gleichen Abständen", "regulär"]))
    u.add_cluster(Cluster(["zutreffend", "unbestritten", "wahr", "nicht strittig", "kein Vertun (es gibt da ...) (ugs.)", "keine Frage! (ugs.)", "unumstritten", "unangefochten", "unstrittig", "unstreitig", "erwiesen"]))
    u.add_cluster(Cluster(["inkorrekt", "ungebührlich", "unfein", "nicht korrekt", "unangemessen", "Wie kann man nur! (ugs.)", "unmöglich (ugs.)", "unstatthaft", "ungehörig (Hauptform)", "gehört sich nicht", "gegen die Etikette", "unmanierlich", "taktlos", "ungeziemend", "deplatziert", "unangebracht", "unsachlich", "fehl am Platz", "nicht angebracht", "gegen den guten Ton verstoßend", "daneben (ugs.)", "unziemlich (geh.)", "unschicklich", "unpassend"]))
    u.add_cluster(Cluster(["direkt", "unbeschönigt", "(einmal ganz) undiplomatisch (fig.)", "rundheraus", "offen", "schonungslos", "unumwunden", "unverhohlen", "unverblümt", "in aller Offenheit", "schlankweg (ugs.)", "(jemandem etwas) ins Gesicht (sagen)"]))
    u.add_cluster(Cluster(["nett", "freundlich", "charmant", "gefällig"]))
    u.add_cluster(Cluster(["(da) hört sich doch alles auf! (ugs.)", "hanebüchen", "heftig! (ugs.)", "kaum zu fassen (ugs.)", "(eine) Frechheit", "unmöglich (ugs.)", "das Allerletzte (ugs.)", "(etwas) geht auf keine Kuhhaut (ugs.)", "nichts für schwache Nerven (übertreibend)", "(dazu) fällt einem nichts mehr ein (ugs.)", "also so etwas! (ugs.)", "unglaublich", "man fasst es nicht! (ugs.)", "das ist (ja wohl) die Höhe! (ugs.)", "(da) bleibt einem die Spucke weg (ugs.", "fig.)", "unsäglich", "(eine) Zumutung! (ugs.)", "(das) schlägt dem Fass die Krone ins Gesicht (ugs.", "salopp", "scherzhaft-ironisch)", "ja gibt's denn sowas!? (ugs.)", "dreist", "haarsträubend", "(etwas) spottet jeder Beschreibung", "unverschämt", "(das) setzt dem ganzen die Krone auf! (ugs.)", "skandalträchtig", "jeder Beschreibung spotten", "hagebüchen (veraltet)", "(ein) starkes Stück", "nicht zu fassen (ugs.", "Hauptform)", "(eine) Unverschämtheit", "das Letzte (ugs.)", "(das ist) der Gipfel der Unverschämtheit (ugs.)", "bodenlos (ugs.)", "(ein) dicker Hund (ugs.", "fig.)", "unerhört", "(das) schlägt dem Fass den Boden aus! (ugs.)"]))
    u.add_cluster(Cluster(["unhaltbar", "fehlerhaft", "unsachgemäß", "nicht haltbar", "inkorrekt", "verkehrt (ugs.)", "nicht zutreffend", "unrichtig", "irrig (geh.)", "nicht zutreffen", "nicht korrekt", "unzutreffend", "nicht richtig", "falsch (sein)", "nicht den Tatsachen entsprechen(d)", "unkorrekt"]))
    u.add_cluster(Cluster(["gern", "freudig", "bereitwillig (Hauptform)", "gerne", "selbstverständlich", "no na (ugs.", "österr.)", "sicherlich", "anstandslos", "selbstredend", "natürlich (ugs.)", "sicher", "selbstverfreilich (ugs.)"]))
    u.add_cluster(Cluster(["maßgebend", "mustergültig"]))
    u.add_cluster(Cluster(["am Stück", "aufeinanderfolgend", "hintereinander", "hintereinanderweg", "ohne Pause", "ohne Unterbrechung", "aufeinander folgend", "in Serie", "nacheinander", "in Folge", "in einem durch"]))
    u.add_cluster(Cluster(["unabänderlich", "kontinuierlich", "immer wieder", "invariabel", "ständig", "inert", "konstant", "stetig", "invariant (fachspr.)", "beständig", "feststehend", "gleichbleibend", "unveränderlich", "jederzeit"]))
    u.add_cluster(Cluster(["ausführlich", "in Füllle", "ergiebig", "reichhaltig", "üppig", "füllig", "reichlich", "opulent", "ausgiebig"]))
    u.add_cluster(Cluster(["verbos (geh.", "lat.)", "wortreich", "ausführlich", "breit", "mit vielen Worten"]))
    u.add_cluster(Cluster(["soziopathisch", "gnadenlos", "erbarmungslos", "kaltblütig", "unbarmherzig", "ohne mit der Wimper zu zucken (ugs.", "fig.)", "ungerührt", "skrupellos", "unerbittlich", "kaltlächelnd", "mitleidlos", "inquisitorisch (geh.", "fig.)", "schonungslos", "ohne Gnade und Barmherzigkeit"]))
    u.add_cluster(Cluster(["fragmentarisch", "lückig (selten)", "verkürzt", "teilweise", "holzschnittartig", "bruchstückhaft", "skizzenhaft", "inkomplett", "lückenhaft", "unvollständig", "unvollkommen", "oberflächlich", "unvollendet"]))
    u.add_cluster(Cluster(["prahlerisch", "prachtvoll", "prächtig", "bombastisch", "üppig", "in Saus und Braus (ugs.)", "opulent", "aus dem Vollen", "auf großem Fuß (ugs.)", "verschwenderisch"]))
    u.add_cluster(Cluster(["gewinnend", "entzückend", "liebreizend", "reizvoll", "bezaubernd", "apart", "aufregend", "faszinierend", "anziehend", "charmant"]))
    u.add_cluster(Cluster(["ordentlich", "...gerecht", "nach Maß", "im Rahmen", "stimmig", "entsprechend", "passend", "anständig", "fair", "adäquat", "angemessen", "gebührend"]))
    u.add_cluster(Cluster(["prächtig", "glorreich"]))
    u.add_cluster(Cluster(["unvollkommen", "unvollständig", "defektiv", "im Ansatz", "verkümmert", "rudimentär", "inkomplett", "nicht ausgebildet"]))
    u.add_cluster(Cluster(["herrschend", "prädominant (geh.", "bildungssprachlich", "lat.)", "dominant", "führend", "vorherrschend", "bestimmend", "maßgebend", "dominierend", "(das) Maß aller Dinge (sein) (Redensart)", "tonangebend", "beherrschend", "maßgeblich"]))
    u.add_cluster(Cluster(["im Ganzen", "vollkommen"]))
    u.add_cluster(Cluster(["prompt (ugs.)", "mit sofortiger Wirkung", "ohne Zeitverzug", "ohne Verzögerung", "spornstreichs (geh.", "veraltend)", "unverzüglich", "postwendend", "wie aus der Pistole geschossen (ugs.)", "unmittelbar", "ohne zeitliche Verzögerung", "instantan (geh.)", "fix (ugs.)", "sofortig", "umgehend", "sofort", "schnurstracks"]))
    u.add_cluster(Cluster(["grundlegend", "Zünglein an der Waage", "kritisch (für)", "wesentlich", "maßgeblich", "bestimmend", "entscheidend", "ausschlaggebend"]))
    u.add_cluster(Cluster(["okay (ugs.)", "adäquat", "in Ordnung", "OK (ugs.)", "passabel", "fair", "vertretbar", "akzeptabel"]))
    u.add_cluster(Cluster(["entgegenkommend", "sozialverträglich (ironisch-sarkastisch) (ugs.)", "konziliant (geh.)", "verbindlich", "zuvorkommend (Hauptform)", "freundlich", "galant", "diplomatisch", "höflich"]))
    u.add_cluster(Cluster(["wie Laternenpfahl ganz unten (ugs.)", "schal (Bier", "Limonade)", "muffig", "abgestanden", "lasch", "fad", "labberig (ugs.", "regional)", "fade", "vermufft"]))
    u.add_cluster(Cluster(["perpetuell (selten)", "für immer", "unaufhörlich", "unendlich", "perpetuierlich (selten)", "fortwährend", "dauerhaft", "immer während", "auf ewig (geh.)", "ewiglich (veraltet)", "in Ewigkeit (geh.)", "ewig", "in alle Ewigkeit (geh.)"]))
    u.add_cluster(Cluster(["Vorwärts...", "progressiv", "voran", "vorwärts", "weiter", "nach vorn"]))
    u.add_cluster(Cluster(["ausgeglichen", "gleichmäßig", "gleichförmig", "symmetrisch"]))
    u.add_cluster(Cluster(["erwiesen", "bewiesen", "erprobt", "anerkannt"]))
    u.add_cluster(Cluster(["unsäglich", "kläglich", "erbärmlich", "schäbig", "armselig", "würdelos", "(ein) Trauerspiel", "mitleiderregend (fig.)", "bemitleidenswert", "unwürdig", "nichtswürdig", "jämmerlich"]))
    u.add_cluster(Cluster(["vorzüglich", "unbeschreiblich", "exquisit", "hervorragend", "exzellent", "süperb", "superb"]))
    u.add_cluster(Cluster(["unangefochten", "unübertroffen"]))
    u.add_cluster(Cluster(["unbegrenzt", "unaufhörlich", "endlos", "unendlich groß", "ad infinitum (geh.", "lat.)", "infinit (geh.", "lat.)"]))
    u.add_cluster(Cluster(["Sahne (ugs.)", "1A (ugs.)", "der Hit (ugs.)", "nicht schlecht (ugs.)", "bombig (ugs.)", "spitze (ugs.)", "zum Reinlegen (ugs.)", "hasenrein (ugs.)", "leiwand (ugs.", "österr.)", "dufte (ugs.)", "tofte (ugs.)", "eine Wucht (ugs.", "veraltet)", "genial (ugs.)", "sauber (ugs.)", "prima (ugs.)", "geil (ugs.)", "astrein (ugs.)", "leinwand (ugs.", "österr.)", "super (ugs.)", "toll", "phatt (ugs.", "Jargon)", "tipptopp (ugs.)", "erste Sahne (ugs.)", "klasse (ugs.)", "doll (ugs.)", "fantastisch", "bombastisch (ugs.)", "phantastisch", "allererste Sahne (ugs.)", "großartig", "töfte (ugs.", "ruhrdt.)", "stark (ugs.)", "cool (ugs.)", "knorke (ugs.", "berlinerisch", "veraltet)"]))
    u.add_cluster(Cluster(["aus dem einzigen Grund (dass)", "einzig", "und sei es nur", "schier", "nichts weiter als", "allein", "alleinig", "ausschließlich", "bloß", "einzig und allein", "nur (Hauptform)", "lediglich", "nichts als"]))
    u.add_cluster(Cluster(["mädchenhaft", "anständig", "unberührt", "rein", "jungfräulich", "unbefleckt (bibl.)", "unverdorben", "keusch", "sittsam", "unschuldig", "züchtig", "unbescholten"]))
    u.add_cluster(Cluster(["gewissenhaft", "exakt", "korrekt", "genau", "präzise", "haargenau (ugs.)", "prägnant", "präzis", "akkurat", "richtig", "fehlerfrei"]))
    u.add_cluster(Cluster(["beziehungsweise", "und zwar", "mehr als das", "bzw. (Abkürzung)", "mehr noch", "eher", "eigentlich", "genauer", "genauer gesagt", "(oder) vielmehr", "respektive (geh.", "lat.)", "(oder) besser gesagt", "resp. (Abkürzung)"]))
    u.add_cluster(Cluster(["von grundlegender Bedeutung", "wesentlich", "fundamental", "von essentieller Bedeutung", "substanziell", "prinzipiell", "von essenzieller Bedeutung", "wichtig", "die Grundlage bildend", "elementar", "Grund- (z.B. Grundkenntnisse)", "basal (fachspr.)", "essenziell", "primär", "essentiell", "von elementarer Bedeutung", "eminent (geh.)", "grundlegend"]))
    u.add_cluster(Cluster(["entmutigt sein", "die Ohren hängen lassen (ugs.)", "kraftlos", "die Flügel hängen lassen (ugs.)", "mutlos sein"]))
    u.add_cluster(Cluster(["Mitleid erregend", "bemitleidenswert", "jammervoll", "armer Tropf (veraltend)", "heruntergekommen", "letztklassig (ugs.", "österr.)", "hoffnungslos", "traurige Gestalt", "bedauernswert (Hauptform)", "beklagenswert", "unglücklich", "arm", "arm dran (ugs.", "ruhrdt.)", "kläglich", "miserabel (geh.)", "armer Teufel (ugs.)", "zu bedauern (sein)", "jämmerlich", "armselig", "erbarmungswürdig (geh.)", "armes Schwein (ugs.)", "arme Sau (derb)", "bejammernswert (fachspr.)", "erbärmlich", "armer Kerl"]))
    u.add_cluster(Cluster(["ausgemacht", "festgelegt", "geregelt", "verbindlich", "festgesetzt", "klar"]))
    u.add_cluster(Cluster(["fest", "ehern", "knüppelhart (ugs.)", "knallhart (ugs.)", "hart", "standhaft"]))
    u.add_cluster(Cluster(["so gut wie", "schon fast (ugs.)", "eher", "praktisch", "eigentlich"]))
    u.add_cluster(Cluster(["außergewöhnlich", "extraordinär", "hervorragend", "eminent", "außerordentlich"]))
    u.add_cluster(Cluster(["grausam", "roh", "hart", "wild"]))
    u.add_cluster(Cluster(["in (ersten) Ansätzen", "halbwegs (ugs.)", "einigermaßen", "im Ansatz", "ansatzweise", "in Grundzügen"]))
    u.add_cluster(Cluster(["üblich", "man kennt das (von) (ugs.", "Redensart)", "herkömmlich", "weit verbreitet", "klassisch", "zum täglichen Brot gehören", "weitverbreitet", "normal", "tägliches Brot (sein)", "(ein)geübt (fig.)", "häufig", "kein Einzelfall", "konventionell", "nicht selten", "an der Tagesordnung (fig.)", "die Regel (sein)", "alltäglich", "ortsüblich", "gewöhnlich", "handelsüblich (fig.)", "gang und gäbe", "gängig", "verbreitet", "geläufig", "gebräuchlich"]))
    u.add_cluster(Cluster(["lasch (ugs.)", "schlabberig (Händedruck) (ugs.", "fig.)", "lahm (ugs.", "fig.)", "schlaff", "unentschieden", "flau", "schlapp (ugs.)"]))
    u.add_cluster(Cluster(["gehaltvoll", "nährstoffreich", "nahrhaft", "kalorienreich", "reichhaltig", "nährend", "mächtig (ugs.)", "sättigend"]))
    u.add_cluster(Cluster(["immobil", "unbeweglich", "unveränderlich", "rigide", "statisch", "starr", "bewegungslos", "steif", "feststehend"]))
    u.add_cluster(Cluster(["frei zum Munde heraus (ironisch altertümelnd) (geh.)", "geradeheraus", "unverblümt", "(frei) von der Leber weg", "offen", "einfach drauflos (ugs.)", "unverhohlen", "ohne Hemmung", "auf gut Deutsch (ugs.", "fig.)", "frei heraus", "rundheraus", "frank und frei", "(so) wie (jemandem) der Schnabel gewachsen ist", "ungeniert"]))
    u.add_cluster(Cluster(["ohne Gewissen", "skrupellos", "gewissenlos"]))
    u.add_cluster(Cluster(["fürwahr (geh.", "veraltend)", "gewiss", "allerdings!", "das ist allerdings richtig", "in der Tat", "stimmt allerdings", "wohl wahr", "durchaus zutreffend"]))
    u.add_cluster(Cluster(["unrichtig", "falsch", "unwahr", "gelogen", "nichts Wahres dran (ugs.)", "wahrheitswidrig"]))
    u.add_cluster(Cluster(["unproblematisch", "unkompliziert", "leicht verständlich", "geschenkt (ugs.)", "einfach", "primitiv", "simpel", "banal", "leicht"]))
    u.add_cluster(Cluster(["verlässlich", "währschaft (schweiz.)", "reliabel (fachspr.)", "zuverlässig", "vertrauenerweckend", "man kann darauf zählen", "solide", "ordentlich", "integer (Person)"]))
    u.add_cluster(Cluster(["betont", "in aller Deutlichkeit", "akzentuiert (geh.)", "angelegentlich (geh.)", "bestimmt", "klar und deutlich", "ausdrücklich", "forsch", "zugespitzt", "klar", "emphatisch", "kategorisch", "unmissverständlich", "mit (großer) Bestimmtheit", "entschieden", "energisch", "mit Nachdruck", "dringlich", "klar und unmissverständlich", "nachdrücklich", "prononciert (geh.)", "eindeutig", "explizit", "deutlich"]))
    u.add_cluster(Cluster(["sozusagen", "wenn man so will", "gleichsam", "im Grunde", "eigentlich", "an sich (ugs.)", "praktisch", "weitestgehend", "gewissermaßen", "im Prinzip", "an und für sich (ugs.)", "wenn Sie so wollen", "fast (wie)", "quasi", "so gut wie (ugs.)"]))
    u.add_cluster(Cluster(["interoperabel (IT-Technik)", "passgenau", "dialogfähig (fachspr.)", "kongruent", "passend", "kompatibel (IT-Technik)", "zusammenpassend", "verträglich", "konvergent", "vereinbar"]))
    u.add_cluster(Cluster(["ehern", "fix", "steht fest", "fest", "gefestigt"]))
    u.add_cluster(Cluster(["offen", "ungeschützt", "(wie) auf dem Präsentierteller (ugs.)"]))
    u.add_cluster(Cluster(["klar und deutlich", "eindeutig", "ganz klar (ugs.)", "klipp und klar (ugs.)", "unzweifelhaft", "klar und unmissverständlich (floskelhaft)", "keinen Zweifel lassen (an)", "unmissverständlich", "klar"]))
    u.add_cluster(Cluster(["offen", "nicht zugesperrt", "unabgeschlossen", "unverschlossen", "unverriegelt", "unversperrt", "nicht abgeschlossen", "aufgesperrt", "auf (ugs.)", "nicht zugeschlossen"]))
    u.add_cluster(Cluster(["vakant", "unbesetzt (Arbeitsplatz)", "nicht besetzt", "frei", "ausgeschrieben (Stelle)", "offen", "in der Ausschreibung", "zu besetzen"]))
    u.add_cluster(Cluster(["vertikal", "aufrecht", "senkrecht (aufgerichtet)", "aufrecht stehend", "lotrecht"]))
    u.add_cluster(Cluster(["in der Regel", "üblicherweise", "für gewöhnlich (geh.)", "landläufig", "normal (Adv.) (ugs.", "salopp)", "gemeinhin (geh.)", "standardmäßig", "in aller Regel", "im Normalfall", "gemeiniglich (geh.", "veraltend)", "typischerweise", "im Regelfall", "von Haus aus", "normalerweise (Hauptform)", "gewöhnlich"]))
    u.add_cluster(Cluster(["eher", "lieber", "mit höherer Wahrscheinlichkeit", "mehr", "vielmehr"]))
    u.add_cluster(Cluster(["kaum", "soeben noch", "bald (ugs.)", "fast", "soeben", "kurz vor knapp (ugs.)", "nahezu", "annähernd", "knapp", "gerade noch (ugs.)", "auf Kante genäht (ugs.)", "haarscharf", "beinahe", "um ein Haar (ugs.)", "fünf vor zwölf (ugs.)", "so gut wie"]))
    u.add_cluster(Cluster(["wohlwollend", "liebenswürdig", "wohlgesinnt", "entgegenkommend", "gut gesinnt"]))
    u.add_cluster(Cluster(["ohne langes Überlegen", "entschlossen", "feste (ugs.)", "forsch", "beherzt", "ordentlich (ugs.)", "tüchtig", "zupackend"]))
    u.add_cluster(Cluster(["in Gänze", "allesamt", "durch die Bank (ugs.)", "alle", "wie sie da sind", "durchgängig", "komplett", "pauschal", "hundertprozentig", "restlos", "in jeder Richtung", "durchweg", "alle", "wie sie da waren", "ohne Ausnahme", "samt und sonders", "praktisch alle", "einstimmig", "alle miteinander", "vollzählig", "ausnahmslos", "generell", "gesamt", "durchwegs (süddt.", "österr.)", "vollständig", "in Bausch und Bogen (ugs.)"]))
    u.add_cluster(Cluster(["überzeugend", "richtig", "authentisch", "unverfälscht", "echt", "veritabel", "unverändert", "wahrhaftig", "wahr"]))
    u.add_cluster(Cluster(["unglaublich", "unglaubwürdig (Hauptform)", "weder Hand noch Fuß haben (fig.)", "fraglich", "nichts dran (ugs.)", "kann bezweifelt werden", "darf man bezweifeln", "das kann mir (doch) keiner erzählen(", "dass ...)! (ugs.", "Spruch)", "unplausibel", "(nur) heiße Luft (ugs.)", "zweifelhaft", "nicht einleuchtend", "unglaubhaft", "fragwürdig", "ohne Wahrheitsgehalt"]))
    u.add_cluster(Cluster(["z. T.", "teilweise", "mitunter", "teils", "von Fall zu Fall", "hier und da (ugs.)", "selektiv", "partiell", "hie und da (ugs.)", "stellenweise", "zum Teil", "in einem bestimmten Ausmaß", "im Einzelfall", "in einzelnen Fällen"]))
    u.add_cluster(Cluster(["wunderbar", "wundervoll", "dass es eine (rechte) Freude ist (literarisch)", "Ich kann mein Glück noch gar nicht fassen! (ugs.", "Spruch)", "famos", "herrlich", "brillant", "prächtig", "ein Gedicht (emphatisch)", "glänzend", "splendid", "(eine) wahre Wonne (ugs.)", "genial"]))
    u.add_cluster(Cluster(["autoritativ", "amtlich", "maßgebend"]))
    u.add_cluster(Cluster(["zeitnah (Jargon)", "schleunigst", "schnellstmöglich", "so schnell wie möglich (Hauptform)", "unverzüglichst", "möglichst sofort", "lieber heute als morgen", "eiligst", "auf schnellstem Wege", "umgehendst", "möglichst schnell", "auf dem schnellsten Weg", "asap (engl.)", "am besten sofort"]))
    u.add_cluster(Cluster(["gierig", "konsumistisch (geh.)", "unersättlich", "(dem) schnöden Mammon frönen (geh.", "variabel)", "habsüchtig", "gewinnsüchtig", "(dem) Geld hinterherjagen (ugs.", "variabel)", "den Hals nicht vollkriegen können (ugs.", "variabel)", "geldgeil (ugs.)", "raffgierig", "profitsüchtig", "geldgierig", "unbescheiden", "unverschämt", "wie die Aasgeier (ugs.)", "habgierig", "materialistisch", "konsumgeil (ugs.)", "besitzgierig"]))
    u.add_cluster(Cluster(["ähnlich", "übereinstimmend", "gleichliegend", "homolog", "entsprechend"]))
    u.add_cluster(Cluster(["spärlich", "bescheiden", "anspruchslos", "karg", "unprätentiös", "spartanisch", "uneitel", "genügsam", "modest (veraltet)", "schlicht", "frugal", "einfach", "unverwöhnt"]))
    u.add_cluster(Cluster(["eremitenhaft", "einsam", "solo", "allein", "wie ein Eremit", "zurückgezogen", "wie ein Einsiedler", "eremitisch", "(ganz) für sich"]))
    u.add_cluster(Cluster(["vollendet", "bestmöglich", "Traum...", "wie kein zweiter", "der Weisheit letzter Schluss (ugs.)", "Spitzen...", "perfekt", "ideal", "(absolut) spitze", "wie gemalt (ugs.)", "keine Wünsche offenlassend", "das Gelbe vom Ei (ugs.", "fig.", "sprichwörtlich)", "vollkommen", "(das) Beste vom Besten", "optimal (Hauptform)", "bestens"]))
    u.add_cluster(Cluster(["abundant (geh.)", "massig (ugs.)", "waggonweise", "reihenweise", "reichhaltig", "in großer Zahl", "zuhauf (geh.)", "vielzählig", "unzählig", "eine Menge Holz (ugs.", "fig.)", "zahlreich", "üppig", "im Überfluss", "massenweise", "Legion sein (geh.)", "viel", "unbegrenzt", "massenhaft", "reich", "in Hülle und Fülle (ugs.)", "haufenweise", "in rauen Mengen (ugs.)", "wie Sand am Meer (ugs.)", "reichlich", "en masse (geh.", "franz.)"]))
    u.add_cluster(Cluster(["deutlich", "allerhand (ugs.)", "ausgeprägt", "jede Menge (ugs.)", "viel", "weit", "eine gehörige Portion (ugs.)", "arg", "ziemlich", "sehr", "enorm", "ausnehmend", "ein gerüttelt Maß (an)", "haushoch", "wesentlich", "ordentlich was (ugs.)", "beträchtlich", "immens (geh.)", "tierisch (ugs.)", "erheblich"]))
    u.add_cluster(Cluster(["trostlos", "desolat", "bedauernswert", "verlassen (ugs.)", "einsam (ugs.)", "beklagenswert"]))
    u.add_cluster(Cluster(["formgewandt", "gesittet", "kultiviert", "gebildet", "soigniert (geh.", "franz.)"]))
    u.add_cluster(Cluster(["ungekocht", "nicht gar", "roh"]))
    u.add_cluster(Cluster(["wichtig", "aussagekräftig", "bedeutsam", "prägnant (ugs.)", "hauptsächlich", "signifikant", "gehaltvoll (geh.)", "wesentlich"]))
    u.add_cluster(Cluster(["alle (ugs.)", "es gibt kein (...) mehr (ugs.)", "zur Neige gegangen (geh.)", "gar (ugs.", "bayr.", "fränk.)", "es hat kein (...) mehr (ugs.", "süddt.)", "leer", "zu Ende gegangen", "nichts mehr da an (ugs.)", "nicht mehr da", "ist kein (...) mehr da (ugs.)", "aufgebraucht", "alle(s) weg (ugs.)", "aus (ugs.)"]))
    u.add_cluster(Cluster(["bestimmt", "besiegelt", "festgelegt", "determiniert"]))
    u.add_cluster(Cluster(["evidenterweise", "klarerweise", "trivialerweise", "selbstverständlich"]))
    u.add_cluster(Cluster(["rechtskräftig", "gültig", "komplett", "valide", "perfekt"]))
    u.add_cluster(Cluster(["unendlich", "unvorstellbar", "unbegrenzt"]))
    u.add_cluster(Cluster(["konsequent", "durchwegs (süddt.", "österr.)", "konsistent", "durchgängig", "aus einem Guss", "durchweg", "einheitlich", "durchgehend"]))
    u.add_cluster(Cluster(["anschaulich", "reell", "echt", "wirklich", "konkret", "auf den Gegenstand bezogen", "fassbar", "anwendungsbezogen", "sachbezogen", "gegenständlich", "greifbar", "bestimmt", "handfest (ugs.)"]))
    u.add_cluster(Cluster(["geordnet", "bereinigt", "säuberlich", "ordentlich", "aufgeräumt"]))
    u.add_cluster(Cluster(["verbraucht (fig.)", "erschlafft", "überanstrengt", "angeschlagen", "verausgabt", "abgeschlagen (schweiz.)", "ausgebrannt (fig.)", "verratzt (ugs.)", "ausgepowert (ugs.)", "abgekämpft", "abgerackert (ugs.)", "ausgelaugt", "entkräftet", "mitgenommen", "abgearbeitet", "fertig (ugs.)", "erschöpft", "kaputt (ugs.)", "gestresst", "schlapp", "abgehetzt", "abgespannt"]))
    u.add_cluster(Cluster(["isoliert", "beziehungslos", "kontaktarm", "ohne soziale Bezüge", "zurückgezogen", "einsam (Hauptform)", "insular (geh.", "fig.)", "ohne (soziale) Kontakte", "kontaktlos"]))
    u.add_cluster(Cluster(["bedacht", "klug", "abgeklärt", "ausgeglichen", "taktisch", "besonnen"]))
    u.add_cluster(Cluster(["geklärt", "abgesprochen", "abgemacht", "geritzt (ugs.)", "verabredet", "festgelegt", "stehen (Jargon)", "feststehen", "vereinbart", "ausgemacht", "perfekt", "beschlossene Sache"]))
    u.add_cluster(Cluster(["führend", "leitend", "federführend"]))
    u.add_cluster(Cluster(["machbarkeitsorientiert", "pragmatisch", "vom Ergebnis her", "sachbezogen", "pertinent", "teleologisch (fachspr.)", "zielorientiert", "anwendungsbezogen", "ergebnisorientiert", "von der Sache her (gesehen)"]))
    u.add_cluster(Cluster(["verlässlich", "anerkannt", "altbewährt", "eingeführt", "kennt man schon", "erprobt", "allseits bekannt", "(der) gute alte (...) (ugs.)", "(der) Klassiker", "gefestigt", "bewährt", "altbekannt", "probat", "etabliert", "alterprobt"]))
    u.add_cluster(Cluster(["nach wie vor", "fortwährend", "immer noch", "bis jetzt (...) pausenlos (variabel)", "noch immer (Hauptform)", "weiterhin (Vergangenheitsperspektive)"]))
    u.add_cluster(Cluster(["der seinesgleichen sucht (geh.)", "unvergleichlich", "einmalig", "alleinig", "wie kein zweiter", "einzigartig", "sui generis (nachgestellt) (geh.", "lat.)", "unikal (fachspr.)", "steht allein (da)", "individuell", "sondergleichen (geh.)", "wie kein anderer", "singulär", "unnachahmlich", "gibt's nur einmal (auf der Welt) (ugs.)", "einzel- / Einzel- (z.B. Einzelstück", "Einzelmeinung)", "nie gekannt", "beispiellos", "nicht vergleichbar", "weißer Rabe (Person) (fig.)", "unverwechselbar (ugs.)", "wie nichts sonst", "kommt nicht wieder (Gelegenheit) (ugs.)", "ohnegleichen", "einzig und allein (Verstärkung)", "einzig"]))
    u.add_cluster(Cluster(["gut beleumdet (geh.", "variabel)", "(einen) guten Ruf zu verlieren haben (variabel)", "anerkannt", "namhaft", "geachtet werden", "profiliert", "geschätzt werden", "(einen) guten Ruf zu verteidigen haben (variabel)", "(einen) guten Leumund haben (variabel)", "(ein) (hohes) Ansehen genießen", "(sich) eines guten Ruf(e)s erfreuen (geh.)", "(gut) angesehen sein (variabel)", "(einen) guten Ruf haben (variabel)", "(einen) guten Namen haben (variabel)", "renommiert", "bestbeleumdet (geh.)", "(einen) guten Ruf genießen (variabel)", "gut beleumundet (sein) (geh.", "variabel)", "(sein) Name hat (in bestimmten Kreisen) einen guten Klang (variabel)", "in einem guten Ruf stehen (variabel)"]))
    u.add_cluster(Cluster(["ganzheitlich", "holistisch", "total", "allumfassend", "gesamtheitlich", "absolut", "uneingeschränkt"]))
    u.add_cluster(Cluster(["extrovertiert", "aufgeschlossen", "weltoffen", "extravertiert (fachspr.)", "nach außen gerichtet"]))
    u.add_cluster(Cluster(["weltabgewandt", "kontaktarm", "einzelgängerisch", "eigenbrötlerisch", "menschenscheu", "kontaktgestört", "isoliert", "kontaktschwach"]))
    u.add_cluster(Cluster(["exotisch", "apart", "fremd", "fremdartig", "fremdländisch", "unbekannt"]))
    u.add_cluster(Cluster(["sequentiell", "gereiht", "aneinandergereiht", "nacheinander", "aufeinander folgend", "sequenziell", "aufeinanderfolgend"]))
    u.add_cluster(Cluster(["ätzend (fig.)", "scharf (fig.)", "unsachlich", "polemisch"]))
    u.add_cluster(Cluster(["begründet", "gerechtfertigt", "substantiiert", "fundiert", "solide", "ausgereift", "untermauert"]))
    u.add_cluster(Cluster(["extrovertiert", "mitteilsam", "kommunikativ", "sein Herz ausschütten (ugs.)", "sein Herz auf der Zunge tragen", "gesprächig", "extravertiert (fachspr.)", "nicht auf den Mund gefallen (ugs.)"]))
    u.add_cluster(Cluster(["persönlich", "unausgewogen", "parteiisch", "unsachlich", "subjektiv", "nicht objektiv", "einseitig"]))
    u.add_cluster(Cluster(["tendenziell", "eher (ugs.)", "verhältnismäßig", "vergleichsweise", "relativ"]))
    u.add_cluster(Cluster(["der Überredung dienend", "gewinnend", "persuasiv", "persuasorisch", "überzeugend", "überredend"]))
    u.add_cluster(Cluster(["allgemeinverständlich", "allgemein verständlich", "leicht verständlich", "leicht erfassbar"]))
    u.add_cluster(Cluster(["heiter", "sonnig", "unbewölkt", "klar", "wolkenlos"]))
    u.add_cluster(Cluster(["keine Ehre im Leib (haben)", "ehrlos", "ohne (jede) Ehre im Leib", "würdelos"]))
    u.add_cluster(Cluster(["tendenziös", "nicht objektiv", "nicht neutral", "einseitig", "parteiisch", "befangen", "vorbelastet", "voreingenommen", "vorurteilsvoll", "unilateral", "unausgewogen"]))
    u.add_cluster(Cluster(["in Balance", "pari", "ausgewogen", "harmonisch", "quitt", "die Interessen beider Seiten berücksichtigend", "ausgeglichen", "im Gleichgewicht"]))
    u.add_cluster(Cluster(["(für jemanden) finanzierbar", "bezahlbar", "im Rahmen", "leistbar (österr.)", "finanziell tragbar", "erschwinglich", "im Limit (ugs.)", "nicht die Welt kosten (ugs.)"]))
    u.add_cluster(Cluster(["dauer...", "bleibend", "Dauer...", "chronisch (fachspr.)", "anhaltend", "langwierig", "dauerhaft", "andauernd"]))
    u.add_cluster(Cluster(["überzeugend", "einleuchtend", "luzid"]))
    u.add_cluster(Cluster(["unbewohnbar", "sanierungsbedürftig", "marode", "auf Abbruch stehen", "baufällig", "in einem erbarmungswürdigen Zustand", "abbruchreif", "heruntergekommen"]))
    u.add_cluster(Cluster(["eklektisch", "elektiv", "auswählend", "selektiv"]))
    u.add_cluster(Cluster(["unbewohnt (Hauptform)", "leerstehend", "ungenutzt", "verwaist", "leer stehend", "frei"]))
    u.add_cluster(Cluster(["flächig", "zweidimensional", "2D"]))
    u.add_cluster(Cluster(["einzigartig (Hauptform)", "einmalig", "unnachahmlich", "unvergleichlich"]))
    u.add_cluster(Cluster(["unvergleichbar", "beispiellos", "(ist) das erste Mal (überhaupt) dass (ugs.)", "präzedenzlos (fachspr.)", "noch nie dagewesen (ugs.)", "ohne Präzedenzfall (fig.)", "ohne Beispiel"]))
    u.add_cluster(Cluster(["prädestiniert", "(jemandem) in die Wiege gelegt", "vorherbestimmt", "determiniert", "vorbestimmt", "vorgezeichnet (Weg)"]))
    u.add_cluster(Cluster(["besser (ugs.)", "lieber", "möglichst", "tunlichst", "nach Möglichkeit"]))
    u.add_cluster(Cluster(["zweckmäßig", "geeignet", "viabel (fachspr.)", "einsetzbar", "passend", "funktionierend", "funktional", "zweckdienlich"]))
    u.add_cluster(Cluster(["sachbezogen", "detachiert (geh.", "veraltet)", "unpersönlich", "sachlich"]))
    u.add_cluster(Cluster(["bereitwillig", "für sein Leben gern", "mit Freuden (geh.)", "von Herzen", "gerne (Hauptform)", "mit Vergnügen", "gern", "am liebsten", "mit Lust und Liebe", "mit Freude"]))
    u.add_cluster(Cluster(["ruiniert", "ungepflegt", "abgeranzt (ugs.)", "verwahrlost", "zerfasert", "muchtig (ugs.", "berlinerisch)", "abgerockt (ugs.", "salopp)", "marode", "verlottert", "in einem schlechten Zustand", "zerlumpt", "verschlissen", "verkommen", "mies", "auf den Hund gekommen (ugs.)", "am Ende", "abgewirtschaftet", "schäbig", "verludert", "abgewrackt (ugs.)", "abgerissen", "zerschlissen", "(herumlaufen) wie ein Penner (derb", "abwertend)", "gammelig (ugs.)", "desolat", "abgetakelt", "verdorben", "vergammelt (ugs.)", "verlumpt", "zerfleddert", "verwildert", "(äußerlich) heruntergekommen (Hauptform)", "abgehalftert", "abgefuckt (derb", "jugendsprachlich)"]))
    u.add_cluster(Cluster(["obsolet (geworden) (geh.)", "nicht mehr erforderlich", "nichtig", "haltlos", "nicht weiter beachtenswert", "(hat sich) erledigt (ugs.)", "nicht (weiter) der Rede wert", "hinfällig", "Wegfall der Geschäftsgrundlage (fachspr.", "juristisch", "veraltet)", "gegenstandslos", "unbegründet", "unhaltbar"]))
    u.add_cluster(Cluster(["amoralisch (geh.)", "sündhaft (religiös)", "unsittlich", "unethisch", "skrupellos (geh.)", "anrüchig", "verwerflich", "fragwürdig", "unmoralisch", "sittenlos"]))
    u.add_cluster(Cluster(["durchgängig", "bündig", "stringent"]))
    u.add_cluster(Cluster(["ganz (ugs.)", "heile (ugs.)", "läuft (noch) (ugs.)", "unbeschädigt", "unversehrt", "funktionsfähig", "mängelfrei", "intakt", "funktionierend", "heil"]))
    u.add_cluster(Cluster(["notdürftig", "konzis", "knapp", "kurz"]))
    u.add_cluster(Cluster(["allgemein verständlich", "in einfacher Sprache", "alltagssprachlich", "gemeinsprachlich (fachspr.)", "in einfachen Worten", "so dahin gesagt (ugs.)", "allgemeinverständlich ausgedrückt", "landläufig (ausgedrückt)", "in informellem Sprachgebrauch", "in Alltagsdeutsch", "im Volksmund", "salopp gesprochen", "vereinfacht gesagt", "in einfachem Deutsch", "einfach gesagt (ugs.)", "umgangssprachlich (Hauptform)", "volksmundlich", "allgemeinverständlich", "einfach ausgedrückt", "in lässiger Redeweise", "in die Tüte gesprochen (ugs.)"]))
    u.add_cluster(Cluster(["bedingt", "eingeschränkt", "unter Vorbehalt", "nur teilweise", "ansatzweise"]))
    u.add_cluster(Cluster(["überheblich (ugs.)", "hypertroph", "überspannt", "gestresst"]))
    u.add_cluster(Cluster(["darauf folgend", "sequenziell", "konsekutiv (fachspr.)", "(zeitlich) folgend", "sich anschließend"]))
    u.add_cluster(Cluster(["platonisch", "keusch", "züchtig", "rein geistig-seelisch", "(sexuell) enthaltsam", "unkörperlich"]))
    u.add_cluster(Cluster(["bei Wasser und Brot (sitzend) (fig.)", "in (polizeilichem) Gewahrsam", "eingesperrt", "festgesetzt", "verhaftet", "im Gefängnis (Hauptform)", "interniert", "gefangen", "hinter schwedischen Gardinen", "in Haft", "im Knast (ugs.)", "eingekerkert", "einsitzen(d)", "hinter Gittern", "in Polizeigewahrsam", "gefangen genommen", "inhaftiert", "eingebuchtet", "hinter Schloss und Riegel"]))
    u.add_cluster(Cluster(["sonnig", "schön", "freundlich (Wetter)", "heiter"]))
    u.add_cluster(Cluster(["verantwortlich", "leitend"]))
    u.add_cluster(Cluster(["hochklassisch", "mustergültig", "klassisch", "höherklassisch", "zeitlos", "vollendet"]))
    u.add_cluster(Cluster(["die Klassik betreffend", "klassisch"]))
    u.add_cluster(Cluster(["erschütterungsfest", "zählebig", "gefestigt", "belastbar", "sicher", "zäh", "leistungsfähig", "hart im Nehmen (ugs.)", "stabil", "abgehärtet"]))
    u.add_cluster(Cluster(["entsprechend", "wie", "in der Art von", "in Bezug auf", "hinsichtlich"]))
    u.add_cluster(Cluster(["verlustbehaftet", "marode", "ermattet", "abgewirtschaftet", "verbraucht"]))
    u.add_cluster(Cluster(["suffizient", "hinlänglich", "gebührend", "genügend", "ausreichend", "zur Genüge", "zufriedenstellend", "auskömmlich", "befriedigend", "hinreichend"]))
    u.add_cluster(Cluster(["bieder", "hausbacken", "brav und bieder", "schlicht", "reizlos"]))
    u.add_cluster(Cluster(["gebildet", "mit akademischem Hintergrund", "studiert", "gelahrt (geh.", "altertümelnd)", "gelehrt", "wissend", "kundig", "belesen", "sachkundig"]))
    u.add_cluster(Cluster(["(psychisch) krank", "fertig (ugs.)", "kaputt (derb)"]))
    u.add_cluster(Cluster(["absacken (ugs.)", "verkommen", "vereinsamen", "versauern"]))
    u.add_cluster(Cluster(["ungeziert", "ungeniert"]))
    u.add_cluster(Cluster(["definit", "bestimmt"]))
    u.add_cluster(Cluster(["paradiesisch", "herrlich", "elysäisch", "himmlisch", "göttlich", "elysisch (lit.)"]))
    u.add_cluster(Cluster(["synchronisiert", "konzertiert", "koordiniert", "abgestimmt", "aufeinander abgestimmt", "abgesprochen"]))
    u.add_cluster(Cluster(["bindend", "verpflichtend", "obligatorisch", "verbindlich"]))
    u.add_cluster(Cluster(["schon", "zugegeben", "(nun) wirklich", "bei allem Verständnis (ugs.)", "(Ihr Wort) in Ehren (aber) (geh.)", "man muss (ganz) einfach sehen (ugs.", "floskelhaft)", "sehr wohl", "bei allem", "was recht ist", "doch", "dein Wort in Gottes Ohr (aber) (ugs.)", "bei allem (gebührenden) Respekt (variabel)", "jedoch", "durchaus", "bei aller Liebe (aber) (ugs.)", "allerdings", "zwar (...) jedoch", "ich muss (schon) sagen", "obwohl", "(etwas) in allen Ehren (geh.)"]))
    u.add_cluster(Cluster(["lange dauernd", "ganz allmählich", "geraume Zeit dauernd", "lange Zeit dauernd", "schleppend", "umständlich", "weitläufig", "nervtötend", "harzig (schweiz.)", "viel Zeit kostend", "langwierig", "mühsam", "zeitraubend", "langatmig", "enervierend (langsam)", "ausgedehnt", "quälend"]))
    u.add_cluster(Cluster(["überhaupt", "schier", "gar"]))
    u.add_cluster(Cluster(["eigenbrötlerisch", "weltfremd", "verschroben", "wunderlich", "kauzig", "sonderbar", "unangepasst"]))
    u.add_cluster(Cluster(["bezaubernd", "fantastisch", "inspirierend", "phantastisch", "magisch"]))
    u.add_cluster(Cluster(["anständig", "sportlich", "fair"]))
    u.add_cluster(Cluster(["ritterlich", "fair"]))
    u.add_cluster(Cluster(["grundlegend", "abstrahierend dargestellt", "im Großen und Ganzen", "grundsätzlich", "erst einmal", "im Wesentlichen"]))
    u.add_cluster(Cluster(["gegeben", "feststehend", "vorbestimmt", "vorgegeben", "gottgegeben"]))
    u.add_cluster(Cluster(["aper (süddt.)", "schneefrei", "offen", "abgetaut"]))
    u.add_cluster(Cluster(["unentschieden", "ratlos", "(sich) nicht sicher", "(auch) nicht wissen", "wie es weitergeht (ugs.)", "unschlüssig", "unentschlossen", "indifferent (geh.)"]))
    u.add_cluster(Cluster(["homophon", "gleichstimmig", "einstimmig", "homofon"]))
    u.add_cluster(Cluster(["unbedingt", "wohl oder übel", "zwangsläufig", "nolens volens (geh.", "lat.)", "unvermeidlich", "notwendigerweise", "notgedrungen", "zwingend"]))
    u.add_cluster(Cluster(["einmalig", "spitze", "Premium...", "überragend", "erstklassig", "hervorragend", "herausragend", "Spitzen...", "hochkarätig"]))
    u.add_cluster(Cluster(["unverändert", "nativ", "unmodifiziert", "naturbelassen", "ohne (weitere) Zutaten"]))
    u.add_cluster(Cluster(["glasig", "leer", "blicklos"]))
    u.add_cluster(Cluster(["real", "tatsächlich", "echt", "effektiv", "wahrhaft", "ohne Scheiß (ugs.)", "so wie es sein soll", "eigentlich", "gelebt", "wirklich", "wahrhaftig", "ehrlich (ugs.)", "lebensecht"]))
    u.add_cluster(Cluster(["eigen", "eindeutig", "bestimmt", "charakteristisch", "spezifisch"]))
    u.add_cluster(Cluster(["ohne Umwege", "Direttissima", "direkte Route"]))
    u.add_cluster(Cluster(["geradezu", "nur so", "praktisch", "buchstäblich", "richtiggehend", "nachgerade (geh.)", "mehr oder weniger", "regelrecht (ugs.)", "förmlich"]))
    u.add_cluster(Cluster(["moralisch", "sittlich", "ethisch"]))
    u.add_cluster(Cluster(["schmählich", "unwürdig", "demütigend", "entehrend", "entwürdigend", "erniedrigend", "schimpflich (geh.)", "schmachvoll", "schändlich"]))
    u.add_cluster(Cluster(["von vorneherein", "per se (geh.", "bildungssprachlich", "lat.)", "von vornherein", "a priori (bildungssprachlich", "lat.)", "von Anfang an", "grundsätzlich"]))
    u.add_cluster(Cluster(["bewährt", "brauchbar"]))
    u.add_cluster(Cluster(["trivialerweise", "erwartungskonform", "natürlicherweise", "erwartungsgemäß", "den Erwartungen entsprechend", "logischerweise (ugs.)", "wenig überraschend", "verständlicherweise", "wie erwartet", "naturgemäß", "der Erwartung entsprechend", "erwartbar", "natürlich", "wie zu erwarten (war)", "selbstverständlich", "wie üblich", "wen wundert's (Einschub) (geh.)", "gewohnt (Adverb)"]))
    u.add_cluster(Cluster(["glatt", "glitschig", "spiegelglatt", "Rutschbahn (fig.)", "schlüpfrig (ugs.)", "rutschig"]))
    u.add_cluster(Cluster(["exotisch", "ungewöhnlich", "außergewöhnlich", "selten"]))
    u.add_cluster(Cluster(["deplorabel", "betrüblich (geh.)", "jammerschade", "bedauernswert", "bedauerlich", "desolat", "schade (ugs.)", "beklagenswert", "ein Jammer (sein)"]))
    u.add_cluster(Cluster(["sequentiell (geh.)", "fortlaufend", "konsekutiv", "aufeinander folgend", "aufeinanderfolgend"]))
    u.add_cluster(Cluster(["dezidiert (geh.)", "rigoros", "erklärt", "entschlossen (Hauptform)", "kategorisch", "mit Bestimmtheit", "unmissverständlich", "bestimmt", "finster entschlossen", "kompromisslos", "gegen alle (/ viele) Widerstände", "resolut", "mit finsterer Entschlossenheit", "energisch", "entschieden (Hauptform)", "mit Entschiedenheit"]))
    u.add_cluster(Cluster(["hervorragend", "eklatant", "hervorstehend", "salient", "herausstehend", "hervorstechend", "hervorspringend"]))
    u.add_cluster(Cluster(["halbseiden", "anrüchig", "berüchtigt", "verrufen", "verschrien", "unseriös", "berühmt-berüchtigt", "zum Himmel stinken (ugs.", "fig.)", "schlecht beleumundet", "unsauber", "nicht ganz koscher (fig.)", "(ein) Gschmäckle haben", "von zweifelhaftem Ruf", "krumm (ugs.", "fig.)"]))
    u.add_cluster(Cluster(["verzweifelt", "desperat (geh.)", "hoffnungslos", "voller Verzweiflung"]))
    u.add_cluster(Cluster(["gesellschaftlich", "sozial", "zwischenmenschlich"]))
    u.add_cluster(Cluster(["zugespitzt", "faserähnlich", "prosenchymatisch (fachspr.)"]))
    u.add_cluster(Cluster(["unzählig", "zahllos", "nicht zählbar", "unzählbar", "nicht abzählbar"]))
    u.add_cluster(Cluster(["aufgeschlossen (für)", "offen", "(ein) hörendes Ohr (haben) (geh.", "biblisch", "fig.)", "zugänglich", "erreichbar", "empfänglich (für)", "ansprechbar (Person)"]))
    u.add_cluster(Cluster(["nicht abgesperrt", "zugänglich", "offen", "frei zugänglich", "öffentlich zugänglich"]))
    u.add_cluster(Cluster(["konsolidiert", "vereinheitlicht", "zusammengeführt", "gefestigt"]))
    u.add_cluster(Cluster(["dynamisch", "mit Musik dahinter (ugs.)", "energievoll", "lebhaft", "kraftvoll", "mit Kawumm (ugs.)", "energisch", "mit Wumm(s) (ugs.)", "energiegeladen", "schwungvoll", "schnittig (geh.)", "unter Dampf stehen(d) (ugs.)", "voll innerer Kraft (geh.)"]))
    u.add_cluster(Cluster(["von kurzer Dauer", "kurz"]))
    u.add_cluster(Cluster(["(sollte) in keiner Sammlung fehlen (ugs.", "formelhaft)", "(ein) Must (engl.)", "zwingend", "de rigueur (geh.", "bildungssprachlich", "franz.)", "unabdingbar", "(ein) Muss", "indispensabel (geh.", "bildungssprachlich", "veraltet)", "nicht (mehr) wegzudenken", "unbedingt dazugehören", "wichtig", "unumgänglich", "zwingend benötigt", "sollte man haben", "(unbedingt) notwendig", "unverzichtbar", "vonnöten", "unentbehrlich", "gehört in jeden (gut sortierten ...) (ugs.", "formelhaft)"]))
    u.add_cluster(Cluster(["am ehesten", "mit Vorliebe", "vorzugsweise (fachspr.)", "am liebsten", "am besten", "bevorzugt (fachspr.)", "optimalerweise (fachspr.)"]))
    u.add_cluster(Cluster(["zu einem Gebiet gehörend", "entsprechend", "in Frage kommend", "dazugehörig", "einschlägig", "dazugehörend"]))
    u.add_cluster(Cluster(["missverständlich", "falsch", "irreführend", "in Täuschungsabsicht"]))
    u.add_cluster(Cluster(["verspannt", "fest", "verkrampft", "steif", "starr"]))
    u.add_cluster(Cluster(["so gut es eben geht", "bestmöglich", "soweit möglich", "weitestmöglich", "nach besten Kräften", "so gut wie möglich", "möglichst optimal"]))
    u.add_cluster(Cluster(["nun einmal", "eben", "halt (ugs.)", "ja nun mal (ugs.)", "nun mal (ugs.)"]))
    u.add_cluster(Cluster(["anziehend", "ähnlich", "affin", "angrenzend", "verwandt"]))
    u.add_cluster(Cluster(["umsetzbar", "erzielbar", "erreichbar", "durchsetzbar"]))
    u.add_cluster(Cluster(["i. d. R.", "in der Regel"]))
    u.add_cluster(Cluster(["dünn", "ausgedünnt", "spärlich", "licht", "schütter"]))
    u.add_cluster(Cluster(["eingeschlossen", "weggesperrt", "eingekerkert", "gefangen", "eingesperrt"]))
    u.add_cluster(Cluster(["astrein (ugs.)", "hasenrein (ugs.)", "tipptopp (ugs.)"]))
    u.add_cluster(Cluster(["trivial", "unschwer", "ganz leicht", "(etwas) kann jeder", "kein Hexenwerk (ugs.", "fig.)", "so einfach wie eins und eins ist zwei", "ganz einfach", "(etwas) im Stehen auf der Treppe erledigen (ugs.", "selten)", "simpel", "jedes Kind kann das", "nichts dabei sein (ugs.)", "pille-palle (ugs.)", "(sehr) einfach", "spielend einfach", "babyleicht (ugs.)", "supereinfach", "nichts leichter als das! (Spruch)", "kinderleicht (Hauptform)", "ich bin jahrelang ... gewesen (ugs.)", "mit dem kleinen Finger (fig.)", "babyeinfach (ugs.)", "keine Kunst (sein)", "nicht allzu viel dazu gehören (zu) (ugs.)", "(sehr) leicht", "ein Leichtes (sein) (geh.)", "keine Hexerei (ugs.", "fig.)", "jeder Idiot kann das (derb)"]))
    u.add_cluster(Cluster(["prinzipbedingt", "aus Prinzip", "naturgemäß"]))
    u.add_cluster(Cluster(["realistisch", "echt"]))
    u.add_cluster(Cluster(["direkt", "eins-zu-eins", "spiegelbildlich", "unverändert"]))
    u.add_cluster(Cluster(["der bevorzugte Lösungsweg", "das Mittel der Wahl", "am besten"]))
    u.add_cluster(Cluster(["besser", "von hoher Kunstfertigkeit", "elaboriert", "reich bestückt", "ausgefeilt", "ausgereift", "hoch entwickelt", "leistungsfähig", "ausgetüftelt", "verfeinert", "bis ins Detail ausgearbeitet"]))
    u.add_cluster(Cluster(["allgemein bekannt", "weithin bekannt", "ubiquitär", "weit verbreitet", "bekannt", "weitverbreitet"]))
    u.add_cluster(Cluster(["(noch) nie dagewesen", "beispiellos (sein)", "einzigartig (sein)", "ohne Beispiel (sein)", "hervorragen", "seinesgleichen suchen", "Ausnahme... (+ Nomen) (sein)", "(sich) auszeichnen (durch)", "(wie es/ihn/sie) die Welt noch nicht gesehen hat", "hervorstechen", "einmalig (sein)", "(ein) Jahrhundert... (sein)"]))
    u.add_cluster(Cluster(["baldigst", "ehestens (österr.)", "nächstmöglich", "möglichst bald", "frühestmöglich", "ehestmöglich (österr.)", "zum baldmöglichsten Zeitpunkt", "am besten gestern (ugs.", "ironisch)", "baldmöglichst", "möglichst früh", "schnellstmöglich", "sobald sich die Gelegenheit ergibt", "so früh wie möglich (Hauptform)", "so schnell wie möglich", "bei nächstbester Gelegenheit", "baldestmöglich (ugs.)", "schnellstens", "zum frühestmöglichen Zeitpunkt", "ehebaldigst (österr.)", "so bald als möglich", "bei nächstmöglicher Gelegenheit", "so bald wie möglich"]))
    u.add_cluster(Cluster(["sauwohl (ugs.)", "pudelwohl (ugs.)", "sehr wohl"]))
    u.add_cluster(Cluster(["markig", "kernig", "prägnant", "kräftig", "kraftvoll", "nicht zimperlich", "plakativ", "schlagkräftig"]))
    u.add_cluster(Cluster(["leer", "substanzlos", "gehaltlos", "ohne Substanz", "ohne Inhalt", "hohl"]))
    u.add_cluster(Cluster(["stimmig", "widerspruchsfrei", "konsistent"]))
    u.add_cluster(Cluster(["ungezwungen", "hemdärmlig (schweiz.)", "hemdärmelig (schweiz.", "österr.)", "bequem", "locker", "salopp", "hemdsärmelig"]))
    u.add_cluster(Cluster(["ganz easy (ugs.)", "aus dem Effeff (ugs.)", "mit leichter Hand", "ohne Anstrengung", "mit links (ugs.)", "ohne die geringste Mühe", "ohne jede Anstrengung", "aus dem Handgelenk (fig.)", "spielerisch", "mit spielerischer Leichtigkeit", "im Schlaf (ugs.", "fig.)", "mit routinierter Gelassenheit", "mal eben so (ugs.)", "mühelos (Hauptform)", "(immer) locker vom Hocker (ugs.", "Spruch)", "mit Leichtigkeit", "mit dem kleinen Finger (fig.)", "ohne Mühe", "lässig", "unangestrengt"]))
    u.add_cluster(Cluster(["interpersonell", "zwischenmenschlich"]))
    u.add_cluster(Cluster(["uneingeschränkt", "ungehindert", "ohne Beschränkung", "frei", "freie Bahn (fig.)", "ohne Limit"]))
    u.add_cluster(Cluster(["bloß", "bar", "nackt", "blank", "frei", "ohne"]))
    u.add_cluster(Cluster(["leer", "ausgehöhlt", "hohl"]))
    u.add_cluster(Cluster(["lukulent (veraltet)", "klar", "lichtvoll"]))
    u.add_cluster(Cluster(["dessen ungeachtet", "indes (geh.)", "zugegebenermaßen", "trotz und allem", "wie auch immer", "freilich", "sicher", "abseits dessen (geh.)", "davon ab (ugs.)", "aber", "trotz alledem", "allein (geh.)", "sicherlich", "zugegeben", "schließlich", "gewiss", "gleichwohl", "trotzdem", "nichtsdestotrotz", "nichtsdestominder", "allerdings (Hauptform)", "dies sei zugestanden (geh.)", "wenigstens", "jedoch", "indessen", "nichtsdestoweniger", "ungeachtet dessen", "immerhin", "jedenfalls", "abgesehen davon", "zumindest"]))
    u.add_cluster(Cluster(["vorerst", "hauptsächlich", "zuvorderst", "vordringlich", "vor allem", "zuvörderst (veraltend)", "vor alledem", "erst einmal", "vorderhand"]))
    u.add_cluster(Cluster(["entsprechend", "andersrum (ugs.)", "andersherum", "dafür", "wiederum", "dagegen", "hingegen", "im Gegenzug", "umgekehrt"]))
    u.add_cluster(Cluster(["umfassend", "immersiv (fachspr.)", "generell", "universell", "allumfassend", "absolut", "unbestimmt", "allgemeingültig", "allgemein gültig", "global"]))
    u.add_cluster(Cluster(["oder (Hauptform)", "beziehungsweise", "andernfalls", "sonst"]))
    u.add_cluster(Cluster(["selber", "solo", "ohne fremde Hilfe", "im Alleingang", "einzeln", "(ganz) alleine", "für sich"]))
    u.add_cluster(Cluster(["simpel", "trivial", "einfach", "leicht"]))
    u.add_cluster(Cluster(["was ganz anderes (ugs.)", "(eine) andere Geschichte (ugs.)", "in keiner Weise vergleichbar", "(eine) ganz andere Sache sein", "(überhaupt) nicht zu vergleichen (sein) (ugs.)", "etwas ganz anderes", "ganz was anderes (sein) (ugs.)", "etwas anderes (Hauptform)", "weitaus besser (geh.", "variabel)", "(ein) anderes Paar Schuhe (sein) (ugs.", "fig.)", "etwas völlig anderes", "(ein) Unterschied wie Tag und Nacht", "(das ist) kein Vergleich (ugs.)", "ganz anders", "(es) liegen Welten zwischen (... und ...)", "nicht zu vergleichen", "grundverschieden", "nicht vergleichbar", "(es) liegen Welten dazwischen", "ganz was anderes (ugs.)", "sehr viel angenehmer (variabel)", "auf einem anderen Blatt stehen (fig.)", "was anderes (ugs.)"]))
    u.add_cluster(Cluster(["vielerorts", "häufig", "in vielen Städten", "an vielen Orten"]))
    u.add_cluster(Cluster(["kräftig", "würzig", "herzhaft", "deftig", "umami (japanisch)", "geschmacksintensiv"]))
    u.add_cluster(Cluster(["ein Übriges tun", "außerdem (Hauptform)", "zu allem Überfluss", "überdies", "zum Überfluss", "(und) zusätzlich", "obendrein", "und", "(und) auch", "mehr noch", "darüber hinaus", "und dazu", "noch dazu"]))
    u.add_cluster(Cluster(["kongruent", "übereinstimmend", "deckungsgleich", "identisch"]))
    u.add_cluster(Cluster(["herausfordernd", "geil (ugs.)", "verführerisch", "zügellos", "sinnlich", "lasziv", "übermütig"]))
    u.add_cluster(Cluster(["ordentlich", "gepflegt", "adrett", "hübsch"]))
    u.add_cluster(Cluster(["vollumfänglich", "allumfassend", "in vollem Umfang"]))
    u.add_cluster(Cluster(["auch", "einfach ausgedrückt", "aka (ugs.", "Jargon)", "alias", "bekannt als", "gemeinhin genannt", "in einfachen Worten", "auch bekannt unter (dem Namen / Begriff)", "vulgo (geh.", "lat.)"]))
    u.add_cluster(Cluster(["ab Werk", "Werkseinstellung", "Auslieferungszustand", "werksseitig eingestellt", "ab Fabrik", "standardmäßig"]))
    return u 